### ISSUE TITLE
Dose this adapter can work normally?

### ISSUE THREAD

**Issue by SchumyHao** [instalator/ioBroker.benq#17]
Hi 
I installed this adapter. Only power on function shown in object.
How this adapter works?

I found you commented out `get_commands`  in https://github.com/Apollon77/ioBroker.benq/blob/master/main.js#L133

I don't know why

**Comment by instalator** [comment]
Нужен переходник rs232 to ethernet

**Comment by SchumyHao** [comment]
Communication is OK, But my adapter only shows power object, I can only open projector, can not close it.
Every thing is normal in your home?

BTW, my projector is W1120, but I checked that the RS232 command is same with all Benq projector.

**Comment by instalator** [comment]
Turn on debag mode adapter and send me log

**Comment by SchumyHao** [comment]
```

benq.0 | 2019-09-07 23:27:36.227 | debug | Send Command:*vol=?#
-- | -- | -- | --
benq.0 | 2019-09-07 23:27:26.217 | debug | Send Command:*vol=?#
benq.0 | 2019-09-07 23:27:16.216 | debug | Send Command:*vol=?#
benq.0 | 2019-09-07 23:27:06.210 | debug | Send Command:*vol=?#
benq.0 | 2019-09-07 23:26:56.203 | debug | redis pmessage io.benq.0.* io.benq.0.info.connection {"val":true,"ack":true,"ts":1567870016200,"q":0,"from":"system.adapter.benq.0","user":"system.user.admin","lc":1567870016200}
benq.0 | 2019-09-07 23:26:56.197 | info | BenQ Connected.
benq.0 | 2019-09-07 23:26:56.175 | debug | BenQ W1070 connect to: 192.168.1.234:23


```
Dose this mean this maybe something wrong with my Arduino hardware?

**Comment by SchumyHao** [comment]
I checked the code. I think this must be my hardware issue.
